-- MySQL Script generated by MySQL Workbench
-- Thu Mar 11 13:22:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`categorias` (
  `idcategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`roles` (
  `idroles` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`personas` (
  `idpersonas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(350) NOT NULL,
  `pass` VARCHAR(350) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `estado` INT(11) NOT NULL,
  `idroles` INT(11) NOT NULL,
  PRIMARY KEY (`idpersonas`),
  CONSTRAINT `idroles`
    FOREIGN KEY (`idroles`)
    REFERENCES `proyecto`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`subcategorias` (
  `idsubcategorias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT(11) NOT NULL,
  `idcategorias` INT(11) NOT NULL,
  PRIMARY KEY (`idsubcategorias`),
  CONSTRAINT `idcategorias`
    FOREIGN KEY (`idcategorias`)
    REFERENCES `proyecto`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`productos` (
  `idproductos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precios` DOUBLE NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `estado` INT(11) NOT NULL,
  `idsubcategorias` INT(11) NOT NULL,
  `idpersonas` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  CONSTRAINT `idsubcategorias`
    FOREIGN KEY (`idsubcategorias`)
    REFERENCES `proyecto`.`subcategorias` (`idsubcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpersonas`
    FOREIGN KEY (`idpersonas`)
    REFERENCES `proyecto`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
