-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 19:54:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto
-- ----------------------------------------------------- 

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `idroles` INT NOT NULL,
  PRIMARY KEY (`idpersonas`),
  CONSTRAINT `idroles`
    FOREIGN KEY (`idroles`)
    REFERENCES `proyecto`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`subcategorias` (
  `idsubcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `idcategorias` INT NOT NULL,
  PRIMARY KEY (`idsubcategorias`),
  CONSTRAINT `idcategorias`
    FOREIGN KEY (`idcategorias`)
    REFERENCES `proyecto`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precios` DOUBLE NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL,
  `idsubcategorias` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  CONSTRAINT `idsubcategorias`
    FOREIGN KEY (`idsubcategorias`)
    REFERENCES `proyecto`.`subcategorias` (`idsubcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`detpedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`detpedidos` (
  `iddetpedidos` INT NOT NULL AUTO_INCREMENT,
  `cant` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  `idproductos` INT NOT NULL,
  PRIMARY KEY (`iddetpedidos`),
  CONSTRAINT `idproductos`
    FOREIGN KEY (`idproductos`)
    REFERENCES `proyecto`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `comentario` VARCHAR(200) NOT NULL,
  `estado` INT NOT NULL,
  `idpersonas` INT NOT NULL,
  `iddetpedidos` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  CONSTRAINT `iddetpedidos`
    FOREIGN KEY (`iddetpedidos`)
    REFERENCES `proyecto`.`detpedidos` (`iddetpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpersonas`
    FOREIGN KEY (`idpersonas`)
    REFERENCES `proyecto`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
